#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

git pull origin master
npm install --prefix CloudPlayer.Client/client/dist/
npm run build --prefix client
cp -r ~/CloudPlayer/CloudPlayer.Client/client/dist/. /var/www/cloudplayer.liborb.com/