#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

git pull origin master
cd ~/CloudPlayer/CloudPlayer.Server/CloudPlayerAPI/bin/Release/netcoreapp3.1
tmux new-session -d -s "CloudPlayer" ./DONTRUN-build-run-server